exports.ModificationType = {
  ADDED_IMAGES: 'ADDED_IMAGES',
  SELECTED_IMAGES: 'SELECTED_IMAGES',
  ASSIGNED_ALBUM: 'ASSIGNED_ALBUM',
  EDITED_ALBUM: 'EDITED_ALBUM',
  SOFT_DELETED_ALBUM: 'SOFT_DELETED_ALBUM',
  RECOVERED_ALBUM: 'RECOVERED_ALBUM',

  EDITED_CLIENT: 'EDITED_CLIENT',
  SOFT_DELETED_CLIENT: 'SOFT_DELETED_CLIENT',
  RECOVERED_CLIENT: 'RECOVERED_CLIENT',

  EDITED_USER: 'EDITED_USER',
  SOFT_DELETED_USER: 'SOFT_DELETED_ALBUM',
  RECOVERED_USER: 'RECOVERED_USER'
};